var path=require('path')

module.exports={
    entry:{
        app:'./src/app'
    },
    output:{
        path:path.resolve(__dirname,'dist'),
        publicPath:'./dist/',
        filename:'[name].bundle.js'
    },
    module:{
        rules:[
            {
                test:/\.css$/,
                use:[
                    {
                        loader:'style-loader',
                        options:{
                            insertInto:"#app",
                            singleton:true,
                            transform:'./src/dealcss.js'
                        }
                    },
                    {
                        loader:'css-loader'
                    }
                ]
            }
        ]
    }
}